kind: Application
apiVersion: argoproj.io/v1alpha1
metadata:
  name: nginx
  namespace: argocd
spec:
  project: default
  source:
    repoURL: "https://github.com/Madhan152004/Argocd.git"
    targetRevision: main
    path: Applications
  destination:
    server:
    namespace: default
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
    - CreateNamespace=true
